### ISSUE TITLE
Update HTTP dependency to ^0.13.0

### ISSUE THREAD

**Issue by filippkowalski** [jg-l/metadata_fetch#27]
Recently there was a big update in Firebase dependencies, making a lot of libraries having conflicts with other outdated dependencies. 

Can we update this library to use `http: ^0.13.0`?

Also, really appreciate your work with this!

**Comment by MagTuxGit** [comment]
http.get takes Uri now. This is the only change needed.

**Comment by jg-l** [comment]
Will have to update the dependncies to null-safety this weekend, `http` would be included in that update
