### ISSUE TITLE
Use regex to strip the first image from JSON-LD Schema

### ISSUE THREAD

**Issue by jg-l** [jg-l/metadata_fetch#4]
Instead of risking runtime errors with how JSON-LD is structured (non-standard, and not very straightfoward), we could opt to do a regex search on the first image we find on the data.

@phranck What do you think?

**Comment by phranck** [comment]
@jg-l That might be an option. If you like you can implement it in a feature branch, open a pull request and set me as a reviewer. So I can check and test it. What do you think?

**Comment by jg-l** [comment]
Sounds good to me

**Comment by jg-l** [comment]
I also found this which may help, https://pub.dev/packages/json_schema

**Comment by phranck** [comment]
Hm... Isn't that a bit of overkill? I'm not a big fan of getting more dependencies into my own code. As less as possible, that's my motto. 😊

So let's see it in a pragmatic way. You are right saying JSON-LD is a very weak standardized form (from its structural point of view). But your current approach is not that wrong, imho. It just has to make ab bit more robust with more options to find an image (e.g. looking for `img`, `image`, `images`, `logo` etc.). Each key can have one value or a list of values.

Like:
```
{
   "image": "http://placehold.it/120x120&text=Test%20image%201"
}
```

And:
```
{
   "image": [
      "http://placehold.it/120x120&text=Test%20image%201",
      "http://placehold.it/240x240&text=Test%20image%201",
      "http://placehold.it/360x360&text=Test%20image%201"
   ]
}
```

**Comment by jg-l** [comment]
I agree with not taking on dependencies.

And yes, you're right! I'll make a feature branch soon
