### ISSUE TITLE
Required Update dependency String Validator to 1.0.0 

### ISSUE THREAD

**Issue by salesandrey** [jg-l/metadata_fetch#45]
Hello, We'd to update the dependency package string validator to 1.0.0.

**Comment by GabriellArthur** [comment]
I also have this problema, does @jg-l have a forecast for the correction?

**Comment by keanallen** [comment]
seems inactive. ive been using this for a year now

**Comment by jg-l** [comment]
> I also have this problema, does @jg-l have a forecast for the correction?

Been inactive, but working up to a release. Thanks

**Comment by SputNikPlop** [comment]
Posting here so that everyone gets an update. The package has been updated, use version 0.4.2
