### ISSUE TITLE
Make default metadata configurable

### ISSUE THREAD

**Issue by cornerman** [jg-l/metadata_fetch#7]
Currently, we return a default metadata document with the url as description and the domain name as title. But this is not always desired. As a user of this library, I want to be aware that the extraction did not work and provide my own default.

For me, it would be okay to return null or if that is not desired, we should have an optional argument in the `extract` method to provide our own default, like `Future<Metadata> extract(String url, {Metadata Function() orElse}) `

**Comment by jg-l** [comment]
I think returning null is sane here. I was shoehorning returning a sane default for my other app, but I will address this soon. Your proposal is saner

**Comment by jg-l** [comment]
With NNBD enabled, null fields are expected. I think this is easier and lends to Dart's strengths of handling nulls.
