### ISSUE TITLE
Not able to fetch data from some URL's 

### ISSUE THREAD

**Issue by deepikat28** [jg-l/metadata_fetch#8]
I am using this library and doing something like this .
 try {
      showProgress(context);
      var data = await extract("https://www.nst.com.my/news/nation/2020/05/595467/man-who-rescued-monitor-lizard-becomes-internet-hero");
    } catch (e) {
      hideProgress(context);
    }

I am getting an exception.

I checked inside the library and the code showing exception at 
JsonLdSchema(document) . 

The issue is coming when i am extracting image from class JsonLdParser . I have attached an snapshot of the exception. 

<img width="675" alt="Screenshot 2020-05-29 at 6 22 39 PM" src="https://user-images.githubusercontent.com/59819841/83261765-81731700-a1d9-11ea-8c19-e9b058717c8f.png">

**Comment by jg-l** [comment]
Thanks for bringing this up. I have to investigate this further.

The JsonLdParser needs more work as of now. I recommend trying OpenGraph or https://github.com/jg-l/metadata_fetch#get-html-metadata as it is much more stable.

`
import 'package:metadata_fetch/metadata_fetch.dart';
import 'package:http/http.dart' as http;

void main () async {

  // Makes a call
  var response = await http.get("https://www.nst.com.my/news/nation/2020/05/595467/man-who-rescued-monitor-lizard-becomes-internet-hero");

  // Covert Response to a Document. The utility function `responseToDocument` is provided or you can use own decoder/parser.
  var document = responseToDocument(response);


  // get metadata
  var data = MetadataParser.OpenGraph(document);
  print(data);


}
`

**Comment by MagTuxGit** [comment]
The fix is merged.
https://github.com/jg-l/metadata_fetch/pull/6
Could you publish a new version, please.

**Comment by jg-l** [comment]
> The fix is merged.
> #6
> Could you publish a new version, please.

Done. 3.0.2 is published.
